// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbHlKrqEQk4oxaja9XchAWY277TzuE6qg',
    appId: '1:336817646337:web:605e683e23fadf007f4900',
    messagingSenderId: '336817646337',
    projectId: 'notification-practice-jh',
    authDomain: 'notification-practice-jh.firebaseapp.com',
    storageBucket: 'notification-practice-jh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwKSdY6IQjUtaJ_lVedMHzxHUlU2h98h8',
    appId: '1:336817646337:android:bb83e7ea64ab64d47f4900',
    messagingSenderId: '336817646337',
    projectId: 'notification-practice-jh',
    storageBucket: 'notification-practice-jh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNXSUooOlXwjKut1j3JJmr-4Mmb6WsUY',
    appId: '1:336817646337:ios:82316d3a8d65ae977f4900',
    messagingSenderId: '336817646337',
    projectId: 'notification-practice-jh',
    storageBucket: 'notification-practice-jh.appspot.com',
    iosClientId: '336817646337-r5j8hjgfra4u4oqm51rn9dcnv0e14vkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationPracticce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjNXSUooOlXwjKut1j3JJmr-4Mmb6WsUY',
    appId: '1:336817646337:ios:82316d3a8d65ae977f4900',
    messagingSenderId: '336817646337',
    projectId: 'notification-practice-jh',
    storageBucket: 'notification-practice-jh.appspot.com',
    iosClientId: '336817646337-r5j8hjgfra4u4oqm51rn9dcnv0e14vkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationPracticce',
  );
}
